CREATE TABLE PIPELINES 
(
id INT AUTO_INCREMENT  PRIMARY KEY,
STARTPOINT VARCHAR(50) NOT NULL,
DESTINATION1 BIT NOT NULL,
DESTINATION2 BIT NOT NULL,
DESTINATION3 BIT NOT NULL,
DESTINATION4 BIT NOT NULL,
DESTINATION5 BIT NOT NULL,
DESTINATION6 BIT NOT NULL,
DESTINATION7 BIT NOT NULL
);

INSERT INTO BIN."PUBLIC".PIPELINES (STARTPOINT, DESTINATION1, DESTINATION2, DESTINATION3, DESTINATION4, DESTINATION5, DESTINATION6, DESTINATION7) 
	VALUES ('1', false, true, true, true, true, false, false);
INSERT INTO BIN."PUBLIC".PIPELINES (STARTPOINT, DESTINATION1, DESTINATION2, DESTINATION3, DESTINATION4, DESTINATION5, DESTINATION6, DESTINATION7) 
	VALUES ('2', false, false, true, true, true, false, false);
INSERT INTO BIN."PUBLIC".PIPELINES (STARTPOINT, DESTINATION1, DESTINATION2, DESTINATION3, DESTINATION4, DESTINATION5, DESTINATION6, DESTINATION7) 
	VALUES ('3', false, false, false, true, true, false, false);
INSERT INTO BIN."PUBLIC".PIPELINES (STARTPOINT, DESTINATION1, DESTINATION2, DESTINATION3, DESTINATION4, DESTINATION5, DESTINATION6, DESTINATION7) 
	VALUES ('4', false, false, false, false, false, false, false);
INSERT INTO BIN."PUBLIC".PIPELINES (STARTPOINT, DESTINATION1, DESTINATION2, DESTINATION3, DESTINATION4, DESTINATION5, DESTINATION6, DESTINATION7) 
	VALUES ('5', false, false, false, false, false, false, false);
INSERT INTO BIN."PUBLIC".PIPELINES (STARTPOINT, DESTINATION1, DESTINATION2, DESTINATION3, DESTINATION4, DESTINATION5, DESTINATION6, DESTINATION7) 
	VALUES ('6', false, false, false, false, false, false, true);
INSERT INTO BIN."PUBLIC".PIPELINES (STARTPOINT, DESTINATION1, DESTINATION2, DESTINATION3, DESTINATION4, DESTINATION5, DESTINATION6, DESTINATION7) 
	VALUES ('7', false, false, false, false, false, false, false);